copyright: Creative Commons Attribution-NonCommercial-ShareAlike 4.0 International
title: My New Hugo Site

theme: github.com/ros4pro/template-hugo

defaultContentLanguage: fr
defaultContentLanguageInSubdir: true
languages:
  fr:
    languageName: Français
    weight: 1
    contentDir: content/french
  en:
    languageName: English
    weight: 2
    contentDir: content/english

markup:
  goldmark:
    renderer:
      unsafe: true